<?php

/**
 * This file is part of Dixlase.
 *
 * Copyright (C) 2026 exc-D inc.
 * https://exc-d.com
 *
 * Dixlase is dual-licensed. You may use this file under either:
 *
 *   (a) the GNU Affero General Public License version 3 or later, as
 *       published by the Free Software Foundation, together with the
 *       Dixlase Plugin and Theme Exception (see
 *       LICENSE-EXCEPTIONS for full exception terms); or
 *
 *   (b) a commercial license agreement obtained from exc-D inc.
 *       (see LICENSE-COMMERCIAL, or contact info@dixlase.org).
 *
 * Unless you have entered into a commercial license agreement, this
 * file is governed by the AGPL terms below.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

namespace App\Services\Plugin;

use App\Contracts\Plugin\SignatureVerifierInterface;
use App\DTO\Plugin\SignatureVerificationResult;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

/**
 * @internal Core use only. Do not reference from plugins/themes
 *
 * Core standard signature verification implementation
 *
 * Ed25519-based cryptographic verification completed within Core alone. Public keys for verification are
 * retrieved from authority.dixlase.net via AuthorityPublicKeyResolver and
 * cached in the local DB. This allows signature verification to work in user environments (DixlaseDevKit
 * not installed).
 *
 * The signature format matches the format produced by an Ed25519 signer
 * tool (typically run by a signing/distribution plugin):
 * Follow the format:
 *   - signature.sig: { algo, key_id, signature(base64), signed_at }
 *   - Signature target: canonical JSON of plugin.json excluding the signing section
 *     (ksort + JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)
 *   - files[]: sha256 hash of each file (excluding plugin.json itself and
 *     .gitignore exclusion patterns)
 *
 * Handling of revoked keys (is_active=false): Only mathematical verification is performed. Plugins signed with expired or
 * revoked keys will return VALID if the signature and content match.
 * This follows the operational policy that "plugins legitimately signed in the past can continue to be used".
 * Follow this operational policy
 */
class CoreSignatureVerifier implements SignatureVerifierInterface
{
    /**
     * Built-in patterns to exclude from signature target.
     *
     * Must exactly match the exclude_patterns in PluginSigner's config/signing.php,
     * with one verifier-only addition: `.dixlase-source.json`. The signer never
     * sees that file (it is generated by Core during install, not present in the
     * plugin's source tree), so adding it on the verifier side only is safe and
     * cannot cause a "missing" false positive.
     * If the exclusion sets differ between signing and verification, it will result in false positives for "extra"/"missing"
     * and be treated as tampering.
     */
    private const DEFAULT_EXCLUDE_PATTERNS = [
        // VCS / CI
        '.git',
        '.github',
        '.gitattributes',
        // Files generated by OS
        '.DS_Store',
        '__MACOSX',
        'Thumbs.db',
        'desktop.ini',
        // IDE / editor settings (varies by user environment, unrelated to functionality)
        '.editorconfig',
        '.vscode',
        '.idea',
        '.fleet',
        '.zed',
        '.nova',
        '.phpactor.json',
        // AI assistant settings (maintainer only, unrelated to distribution behavior)
        'CLAUDE.md',
        'CLAUDE.ja.md',
        '.claude',
        '.mcp.json',
        // Signature file itself (avoid self-hash recursion)
        'signature.sig',
        // Core-managed supply-chain sidecar (transient: written by the
        // marketplace/GitHub download flow, deleted by install()). Sits in the
        // plugin dir during the "downloaded but not yet installed" window when
        // the UI scan runs, so it must be excluded to avoid a false "extra"
        // tampering verdict.
        '.dixlase-source.json',
    ];

    public function __construct(
        protected AuthorityPublicKeyResolver $publicKeyResolver,
    ) {}

    /**
     * Verify plugin signature
     */
    public function verify(string $pluginSlug): SignatureVerificationResult
    {
        $pluginName = Str::studly(str_replace('-', '_', $pluginSlug));
        $pluginPath = base_path("plugins/{$pluginName}");
        $pluginJsonPath = "{$pluginPath}/plugin.json";
        $signaturePath = "{$pluginPath}/signature.sig";

        // When plugin.json does not exist
        if (! File::exists($pluginJsonPath)) {
            return SignatureVerificationResult::unsigned(__('services/plugin/core_signature_verifier.plugin_json_not_found'));
        }

        $pluginData = json_decode(File::get($pluginJsonPath), true);
        if (json_last_error() !== JSON_ERROR_NONE) {
            return SignatureVerificationResult::error(__('services/plugin/core_signature_verifier.plugin_json_parse_failed'));
        }

        if (! isset($pluginData['signing'])) {
            return SignatureVerificationResult::unsigned();
        }

        $declaredKeyId = $pluginData['signing']['key_id'] ?? null;

        if (! File::exists($signaturePath)) {
            return SignatureVerificationResult::unsigned(__('services/plugin/core_signature_verifier.signature_file_not_found'));
        }

        $sigData = json_decode(File::get($signaturePath), true);
        if (! is_array($sigData)) {
            return SignatureVerificationResult::error(__('services/plugin/core_signature_verifier.signature_file_parse_failed'));
        }

        if (empty($sigData['key_id']) || empty($sigData['signature'])) {
            return SignatureVerificationResult::invalid(__('services/plugin/core_signature_verifier.signature_missing_required_fields'));
        }

        $signatureKeyId = $sigData['key_id'];
        $signedAt = $sigData['signed_at'] ?? null;
        $signedBy = $sigData['signed_by'] ?? null;

        // Check if key_id matches between plugin.json and signature.sig
        if ($declaredKeyId !== null && $declaredKeyId !== $signatureKeyId) {
            return SignatureVerificationResult::invalid(__('services/plugin/core_signature_verifier.key_id_mismatch'), [
                'plugin_json_key_id' => $declaredKeyId,
                'signature_key_id' => $signatureKeyId,
            ]);
        }

        // Retrieve public key
        $publicKey = $this->publicKeyResolver->resolve($signatureKeyId);
        if ($publicKey === null) {
            // Network unavailable and no cache → treat as verification pending
            // (require policy side determines pending = reject)
            return new SignatureVerificationResult(
                status: SignatureVerificationResult::STATUS_PENDING,
                type: $this->determineSignatureType($signatureKeyId),
                signedBy: $signedBy,
                signedAt: $signedAt,
                keyId: $signatureKeyId,
                message: __('services/plugin/core_signature_verifier.verification_suspended_no_key'),
            );
        }

        // Detect file tampering
        if (! isset($pluginData['files']) || ! is_array($pluginData['files'])) {
            return SignatureVerificationResult::invalid(__('services/plugin/core_signature_verifier.plugin_json_no_files_section'));
        }

        $tamper = $this->verifyFileHashes($pluginPath, $pluginData['files']);
        if (! $tamper['valid']) {
            return SignatureVerificationResult::invalid(__('services/plugin/core_signature_verifier.plugin_file_tampering_detected'), [
                'mismatched' => $tamper['mismatched'] ?? [],
                'missing' => $tamper['missing'] ?? [],
                'extra' => $tamper['extra'] ?? [],
            ]);
        }

        // Ed25519 signature verification
        try {
            $cryptoValid = $this->verifyEd25519Signature(
                $pluginData,
                $sigData['signature'],
                $publicKey->public_key,
            );
        } catch (\Throwable $e) {
            Log::warning('CoreSignatureVerifier: ed25519 verification error', [
                'key_id' => $signatureKeyId,
                'error' => $e->getMessage(),
            ]);

            return SignatureVerificationResult::error(__('services/plugin/core_signature_verifier.signature_verification_error').$e->getMessage());
        }

        if (! $cryptoValid) {
            return SignatureVerificationResult::invalid(__('services/plugin/core_signature_verifier.signature_mismatch_tampering'));
        }

        return SignatureVerificationResult::valid(
            keyId: $signatureKeyId,
            signedBy: $signedBy,
            signedAt: $signedAt,
            type: $this->determineSignatureType($signatureKeyId),
        );
    }

    /**
     * Whether signature verification is available
     */
    public function isAvailable(): bool
    {
        return true;
    }

    /**
     * Ed25519 signature verification
     *
     * Data to be signed excludes the signing section from plugin.json,
     * with top-level and files[] ksorted before JSON encoding
     * Must exactly match PluginSigner::getDataToSign()
     */
    protected function verifyEd25519Signature(array $pluginData, string $signatureBase64, string $publicKeyEncoded): bool
    {
        $data = $pluginData;
        unset($data['signing']);
        ksort($data);
        if (isset($data['files'])) {
            ksort($data['files']);
        }
        $dataToVerify = json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

        $signatureBinary = base64_decode($signatureBase64);
        $publicKeyBinary = $this->decodeKey($publicKeyEncoded);

        return sodium_crypto_sign_verify_detached($signatureBinary, $dataToVerify, $publicKeyBinary);
    }

    /**
     * Decode "base64:..." or plain base64 string to binary
     */
    protected function decodeKey(string $encoded): string
    {
        if (str_starts_with($encoded, 'base64:')) {
            $encoded = substr($encoded, 7);
        }

        $decoded = base64_decode($encoded, true);
        if ($decoded === false) {
            throw new \RuntimeException('Failed to decode public key from base64');
        }

        return $decoded;
    }

    /**
     * Verify hashes of files[] in plugin.json against actual files
     *
     * @param  array<string, string>  $expectedFiles  files[] section (path => "algo:hash")
     * @return array{valid: bool, mismatched: array<string>, missing: array<string>, extra: array<string>}
     */
    protected function verifyFileHashes(string $pluginPath, array $expectedFiles): array
    {
        $actualFiles = $this->collectFileHashes($pluginPath);

        $missing = array_diff_key($expectedFiles, $actualFiles);
        $extra = array_diff_key($actualFiles, $expectedFiles);
        $mismatched = [];

        foreach ($expectedFiles as $relPath => $expectedHash) {
            if (! isset($actualFiles[$relPath])) {
                continue;
            }
            if ($actualFiles[$relPath] !== $expectedHash) {
                $mismatched[] = $relPath;
            }
        }

        return [
            'valid' => empty($missing) && empty($extra) && empty($mismatched),
            'mismatched' => $mismatched,
            'missing' => array_keys($missing),
            'extra' => array_keys($extra),
        ];
    }

    /**
     * Collect file hashes in the plugin directory
     * Exclude plugin.json itself, signature.sig, and paths excluded by .gitignore
     *
     * @return array<string, string> path => "algo:hash"
     */
    protected function collectFileHashes(string $pluginPath): array
    {
        $files = [];
        $gitignore = $this->parseGitignore($pluginPath);
        $excludePatterns = array_unique(array_merge(
            self::DEFAULT_EXCLUDE_PATTERNS,
            $gitignore['exclude'],
        ));
        $includePatterns = $gitignore['include'];

        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($pluginPath, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::LEAVES_ONLY,
        );

        foreach ($iterator as $file) {
            if ($file->isDir()) {
                continue;
            }

            $relPath = str_replace('\\', '/', str_replace($pluginPath.DIRECTORY_SEPARATOR, '', $file->getPathname()));

            // Same exclusion rules as PluginSigner side:
            //  - Exclude plugin.json itself from files[] (to avoid circular self-hashing)
            //  - Exclude DEFAULT_EXCLUDE_PATTERNS and .gitignore paths,
            //    honoring `!`-prefixed re-include rules from .gitignore
            if ($relPath === 'plugin.json') {
                continue;
            }
            if ($this->shouldExclude($relPath, $excludePatterns, $includePatterns)) {
                continue;
            }

            $files[$relPath] = 'sha256:'.hash_file('sha256', $file->getPathname());
        }

        ksort($files);

        return $files;
    }

    /**
     * Parse .gitignore into exclude / include pattern lists.
     *
     * Mirrors PluginSigner's parser: a line beginning with `!` is a
     * re-include that overrides a previously-matched exclude pattern,
     * matching git's own semantics (e.g. `/resources/assets/*` followed
     * by `!/resources/assets/thumbnail.*` re-includes the thumbnail).
     *
     * @return array{exclude: array<string>, include: array<string>}
     */
    protected function parseGitignore(string $pluginPath): array
    {
        $path = $pluginPath.'/.gitignore';
        if (! File::exists($path)) {
            return ['exclude' => [], 'include' => []];
        }

        $excludes = [];
        $includes = [];
        foreach (explode("\n", File::get($path)) as $line) {
            $line = trim($line);
            if ($line === '' || str_starts_with($line, '#')) {
                continue;
            }
            if (str_starts_with($line, '!')) {
                $includes[] = ltrim(substr($line, 1), '/');

                continue;
            }
            $excludes[] = ltrim($line, '/');
        }

        return ['exclude' => $excludes, 'include' => $includes];
    }

    /**
     * Decide whether a path is excluded from signature verification.
     *
     * A path is excluded only when it matches one of the exclude
     * patterns AND is not re-included by any `!`-prefixed gitignore
     * pattern, mirroring how git resolves overlapping gitignore lines
     * and how PluginSigner picks the files to hash. Diverging from
     * PluginSigner here would re-introduce false "missing"/"extra"
     * tampering verdicts.
     *
     * @param  array<string>  $excludes
     * @param  array<string>  $includes
     */
    protected function shouldExclude(string $path, array $excludes, array $includes): bool
    {
        if (! $this->matchesAny($path, $excludes)) {
            return false;
        }
        if ($this->matchesAny($path, $includes)) {
            return false;
        }

        return true;
    }

    /**
     * Test a path against a list of patterns (wildcard `*` or substring).
     *
     * @param  array<string>  $patterns
     */
    protected function matchesAny(string $path, array $patterns): bool
    {
        foreach ($patterns as $pattern) {
            if (strpos($pattern, '*') !== false) {
                $regex = '/^'.str_replace(['*', '/'], ['.*', '\/'], $pattern).'$/';
                if (preg_match($regex, $path)) {
                    return true;
                }
            } elseif (strpos($path, $pattern) !== false) {
                return true;
            }
        }

        return false;
    }

    /**
     * Determine signature type from key_id (for badge display)
     */
    protected function determineSignatureType(?string $keyId): ?string
    {
        if ($keyId === null) {
            return null;
        }
        if (str_starts_with($keyId, 'dixlase-official') || str_starts_with($keyId, 'dixlase-authority')) {
            return 'official';
        }
        if (str_starts_with($keyId, 'dixlase-verified') || str_starts_with($keyId, 'marketplace')) {
            return 'verified';
        }
        if (str_starts_with($keyId, 'partner-')) {
            return 'partner';
        }

        return null;
    }
}
