{{--
This file is part of Dixlase.

Copyright (C) 2025 exc-D inc.
https://exc-d.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
--}}

@props([
    'modalId' => 'recoveryCodesModal',
    'title' => null,
    'codes' => [],
    'isAutoGenerated' => false,
    'autoOpen' => false,
    'isDynamic' => false, // JavaScriptで動的に表示する場合
    'error' => null, // エラーメッセージ（エラー表示モード）
    'clearSessionRoute' => null, // セッションクリア用ルート（自動生成時のみ）
])

<x-modal :id="$modalId" :title="$error ? __('common.error') : ($title ?? __('two-factor.recovery_codes.title'))" :icon_type="$error ? 'danger' : 'warning'">
    <div class="space-y-4">
        @if($error)
            {{-- エラー表示モード --}}
            <div class="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4">
                <p class="text-sm text-red-800 dark:text-red-200">
                    <i class="fas fa-exclamation-circle mr-2"></i>
                    {{ $error }}
                </p>
            </div>
        @else
            {{-- 回復コード表示モード --}}
            @if($isAutoGenerated)
            <div class="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
                <p class="text-sm text-blue-800 dark:text-blue-200">
                    <i class="fas fa-info-circle mr-2"></i>
                    {{ __('two-factor.recovery_codes.auto_generated_message') }}
                </p>
            </div>
            @endif
            
            <div class="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
                <p class="text-sm text-yellow-800 dark:text-yellow-200">
                    <i class="fas fa-exclamation-triangle mr-2"></i>
                    {{ __('two-factor.recovery_codes.warning') }}
                </p>
            </div>
            
            <div class="bg-gray-50 dark:bg-gray-800 rounded-lg p-4">
                <div id="{{ $modalId }}-codes-list" class="space-y-2 font-mono text-sm">
                    @if(!$isDynamic)
                        @foreach($codes as $code)
                            <div class="p-2 bg-white dark:bg-gray-700 rounded border border-gray-200 dark:border-gray-600 text-center">
                                {{ implode('-', str_split($code, 5)) }}
                            </div>
                        @endforeach
                    @else
                        <!-- JavaScriptで動的に追加 -->
                    @endif
                </div>
            </div>
            
            <div class="flex gap-2">
                <button 
                    type="button"
                    onclick="downloadRecoveryCodesFromModal('{{ $modalId }}')"
                    class="flex-1 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                    <i class="fas fa-download mr-2"></i>{{ __('common.download') }}
                </button>
                <button 
                    type="button"
                    id="{{ $modalId }}-copy-btn"
                    onclick="copyRecoveryCodesFromModal('{{ $modalId }}')"
                    class="flex-1 px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500">
                    <i class="fas fa-copy mr-2"></i>{{ __('common.copy') }}
                </button>
            </div>
            
            <!-- 保管確認チェックボックス -->
            <div class="mt-4 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg">
                <label class="flex items-start cursor-pointer">
                    <input 
                        type="checkbox" 
                        id="{{ $modalId }}-saved-checkbox"
                        onchange="checkRecoveryCodesSavedFromModal('{{ $modalId }}')"
                        class="mt-1 h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded">
                    <span class="ml-3 text-sm text-red-800 dark:text-red-200 font-semibold">
                        <i class="fas fa-exclamation-circle mr-1"></i>
                        {{ __('two-factor.recovery_codes.confirm_saved') }}
                    </span>
                </label>
            </div>
        @endif
    </div>
    
    <x-slot name="footer">
        <button 
            type="button"
            id="{{ $modalId }}-close-btn"
            onclick="closeModal('{{ $modalId }}')"
            @if(!$error) disabled @endif
            class="px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 @if(!$error) opacity-50 cursor-not-allowed @endif">
            {{ __('common.close') }}
        </button>
    </x-slot>
</x-modal>

@if($autoOpen)
@push('scripts')
<script>
    // モーダルを自動表示
    document.addEventListener('DOMContentLoaded', function() {
        openModal('{{ $modalId }}');
    });
</script>
@endpush
@endif

@if($clearSessionRoute)
@push('scripts')
<script>
    // 自動生成モーダルを閉じるときにセッションをクリア
    document.addEventListener('DOMContentLoaded', function() {
        const closeBtn = document.getElementById('{{ $modalId }}-close-btn');
        
        if (closeBtn) {
            closeBtn.addEventListener('click', async function() {
                try {
                    await fetch('{{ $clearSessionRoute }}', {
                        method: 'POST',
                        headers: {
                            'X-CSRF-TOKEN': '{{ csrf_token() }}',
                            'Content-Type': 'application/json',
                            'Accept': 'application/json'
                        }
                    });
                    console.log('[{{ $modalId }}] Recovery codes session cleared');
                } catch (error) {
                    console.error('[{{ $modalId }}] Failed to clear session:', error);
                }
            });
        }
    });
</script>
@endpush
@endif

@once
@push('scripts')
<script>
    // 回復コードモーダル用のグローバル変数
    window.recoveryCodesData = window.recoveryCodesData || {};
    
    // 回復コードをフォーマット（5桁ごとにハイフン）
    function formatRecoveryCode(code) {
        return code.match(/.{1,5}/g).join('-');
    }
    
    // 回復コードを動的に表示（JavaScript用）
    function displayRecoveryCodesInModal(modalId, codes) {
        window.recoveryCodesData[modalId] = codes;
        const container = document.getElementById(modalId + '-codes-list');
        if (container) {
            container.innerHTML = codes.map(code => 
                `<div class="p-2 bg-white dark:bg-gray-700 rounded border border-gray-200 dark:border-gray-600 text-center">${formatRecoveryCode(code)}</div>`
            ).join('');
        }
    }
    
    // エラーメッセージを動的に表示（JavaScript用）
    function displayRecoveryCodesError(modalId, errorMessage) {
        const modal = document.getElementById(modalId);
        if (!modal) return;
        
        // モーダルの内容を取得
        const modalContent = modal.querySelector('.space-y-4');
        if (!modalContent) return;
        
        // エラー表示用HTMLを作成
        const errorHTML = `
            <div class="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4">
                <p class="text-sm text-red-800 dark:text-red-200">
                    <i class="fas fa-exclamation-circle mr-2"></i>
                    ${errorMessage}
                </p>
            </div>
        `;
        
        // モーダルの内容を置き換え
        modalContent.innerHTML = errorHTML;
        
        // モーダルタイトルをエラーに変更
        const modalTitle = modal.querySelector('h3');
        if (modalTitle) {
            modalTitle.textContent = '{{ __("common.error") }}';
        }
        
        // 閉じるボタンを有効化
        const closeBtn = document.getElementById(modalId + '-close-btn');
        if (closeBtn) {
            closeBtn.disabled = false;
            closeBtn.classList.remove('opacity-50', 'cursor-not-allowed');
        }
    }
    
    // 回復コードをダウンロード
    function downloadRecoveryCodesFromModal(modalId) {
        const codes = window.recoveryCodesData[modalId] || [];
        const text = codes.map(code => formatRecoveryCode(code)).join('\n');
        const blob = new Blob([text], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'recovery-codes-' + new Date().toISOString().split('T')[0] + '.txt';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }
    
    // 回復コードをコピー
    function copyRecoveryCodesFromModal(modalId) {
        const codes = window.recoveryCodesData[modalId] || [];
        const text = codes.map(code => formatRecoveryCode(code)).join('\n');
        const copyBtn = document.getElementById(modalId + '-copy-btn');
        const originalHTML = copyBtn.innerHTML;
        
        navigator.clipboard.writeText(text).then(() => {
            // コピー成功：チェックアイコンを表示
            copyBtn.innerHTML = '<i class="fas fa-check mr-2"></i>{{ __("common.copied") }}';
            copyBtn.classList.remove('bg-gray-600', 'hover:bg-gray-700');
            copyBtn.classList.add('bg-green-600', 'hover:bg-green-700');
            
            // 2秒後に元に戻す
            setTimeout(() => {
                copyBtn.innerHTML = originalHTML;
                copyBtn.classList.remove('bg-green-600', 'hover:bg-green-700');
                copyBtn.classList.add('bg-gray-600', 'hover:bg-gray-700');
            }, 2000);
        }).catch(err => {
            console.error('Copy error:', err);
            alert('{{ __("common.copy_failed") }}');
        });
    }
    
    // 回復コード保管確認チェックボックスの状態を監視
    function checkRecoveryCodesSavedFromModal(modalId) {
        const checkbox = document.getElementById(modalId + '-saved-checkbox');
        const closeBtn = document.getElementById(modalId + '-close-btn');
        
        if (checkbox && closeBtn) {
            closeBtn.disabled = !checkbox.checked;
            
            if (checkbox.checked) {
                closeBtn.classList.remove('opacity-50', 'cursor-not-allowed');
            } else {
                closeBtn.classList.add('opacity-50', 'cursor-not-allowed');
            }
        }
    }
</script>
@endpush
@endonce
