{{--
This file is part of Dixlase.

Copyright (C) 2026 exc-D inc.
https://exc-d.com

Dixlase is dual-licensed. You may use this file under either:

  (a) the GNU Affero General Public License version 3 or later, as
      published by the Free Software Foundation, together with the
      Dixlase Plugin and Theme Exception (see
      LICENSE-EXCEPTIONS for full exception terms); or

  (b) a commercial license agreement obtained from exc-D inc.
      (see LICENSE-COMMERCIAL, or contact info@dixlase.org).

Unless you have entered into a commercial license agreement, this
file is governed by the AGPL terms below.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
--}}

@extends('layouts.admin')

@section('content')

    <div class="mx-auto space-y-6">

        <h1 class="text-xl font-semibold text-gray-900 dark:text-gray-100">
            <i class="fas fa-tachometer-alt mr-2"></i>{{ __('admin/dashboard.heading') }}
        </h1>

        {{-- Getting started card --}}
        @if(isset($gettingStarted))
            @include('admin.dashboard._getting-started')
        @endif

        {{-- Site health --}}
        @include('admin.dashboard._site-health')

        {{-- Extension and member overview --}}
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
            @include('admin.dashboard._extension-overview', ['extensionOverview' => $extensionOverview])
            @include('admin.dashboard._member-overview', ['memberOverview' => $memberOverview])
        </div>

        {{-- Recent activity --}}
        @include('admin.dashboard._recent-activity', ['recentActivity' => $recentActivity])

        {{-- Plugin notifications --}}
        @if(count($pluginNotifications) > 0)
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg p-6">
                @include('admin.dashboard._plugin-notifications')
            </div>
        @endif

        {{-- Plugin widgets --}}
        @if(count($pluginWidgets) > 0)
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg p-6">
                @include('admin.dashboard._content-widgets')
            </div>
        @endif

        {{-- System information --}}
        <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg p-6">
            @include('admin.dashboard._system-info')
        </div>

    </div>

    {{-- Auto-generated recovery codes modal --}}
    @if(isset($auto_generated_recovery_codes))
        @include('two-fa.partials.recovery-codes-modal', [
            'modalId' => 'dashboardRecoveryCodesModal',
            'title' => __('two-fa/recovery-code.auto_generated_title'),
            'codes' => $auto_generated_recovery_codes,
            'isAutoGenerated' => true,
            'autoOpen' => true,
            'nextModal' => isset($prompt_passkey_registration) && $prompt_passkey_registration ? 'dashboardPasskeyPromptModal' : null
        ])
    @endif

    {{-- Passkey registration prompt modal --}}
    @if(isset($prompt_passkey_registration) && $prompt_passkey_registration)
        @include('two-fa.partials.passkey-prompt-modal', [
            'modalId' => 'dashboardPasskeyPromptModal',
            'hasRecoveryModal' => isset($auto_generated_recovery_codes) && $auto_generated_recovery_codes ? true : false
        ])
    @endif
@endsection
