{{--
This file is part of Dixlase.

Copyright (C) 2025 exc-D inc.
https://exc-d.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
--}}

@extends('layouts.admin')

@section('content')

    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
            <div class="p-6">
                {{ __("You're logged in!") }}
            </div>

        </div>
         {{__('custom.welcome')}};
         {{__('admin.nav.custom.text')}};
         {{ __('reservation-plugin::admin.nav.reservations.text')}};

    </div>

    <!-- 自動生成された回復コード表示モーダル -->
    @if(session('auto_generated_recovery_codes'))
    <x-modal id="autoGeneratedRecoveryCodesModal" :title="__('two-factor.recovery_codes.auto_generated_title')">
        <div class="space-y-4">
            <div class="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
                <p class="text-sm text-blue-800 dark:text-blue-200">
                    <i class="fas fa-info-circle mr-2"></i>
                    {{ __('two-factor.recovery_codes.auto_generated_message') }}
                </p>
            </div>
            
            <div class="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
                <p class="text-sm text-yellow-800 dark:text-yellow-200">
                    <i class="fas fa-exclamation-triangle mr-2"></i>
                    {{ __('two-factor.recovery_codes.warning') }}
                </p>
            </div>
            
            <div class="bg-gray-50 dark:bg-gray-800 rounded-lg p-4">
                <div class="space-y-2 font-mono text-sm">
                    @foreach(session('auto_generated_recovery_codes') as $code)
                        <div class="p-2 bg-white dark:bg-gray-700 rounded border border-gray-200 dark:border-gray-600 text-center">
                            {{ implode('-', str_split($code, 5)) }}
                        </div>
                    @endforeach
                </div>
            </div>
            
            <div class="flex gap-2">
                <button 
                    type="button"
                    onclick="downloadAutoGeneratedRecoveryCodes()"
                    class="flex-1 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                    <i class="fas fa-download mr-2"></i>{{ __('common.download') }}
                </button>
                <button 
                    type="button"
                    onclick="copyAutoGeneratedRecoveryCodes()"
                    class="flex-1 px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500">
                    <i class="fas fa-copy mr-2"></i>{{ __('common.copy') }}
                </button>
            </div>
            
            <!-- 保管確認チェックボックス -->
            <div class="mt-4 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg">
                <label class="flex items-start cursor-pointer">
                    <input 
                        type="checkbox" 
                        id="autoGeneratedRecoveryCodesSavedCheckbox"
                        onchange="checkAutoGeneratedRecoveryCodesSaved()"
                        class="mt-1 h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded">
                    <span class="ml-3 text-sm text-red-800 dark:text-red-200 font-semibold">
                        <i class="fas fa-exclamation-circle mr-1"></i>
                        {{ __('two-factor.recovery_codes.confirm_saved') }}
                    </span>
                </label>
            </div>
        </div>
        
        <x-slot name="footer">
            <button 
                type="button"
                id="autoGeneratedRecoveryCodesCloseBtn"
                onclick="closeModal('autoGeneratedRecoveryCodesModal')"
                disabled
                class="px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 opacity-50 cursor-not-allowed">
                {{ __('common.close') }}
            </button>
        </x-slot>
    </x-modal>
    @endif
@endsection

@if(session('auto_generated_recovery_codes'))
@push('scripts')
<script>
    // 自動生成された回復コード
    const autoGeneratedCodes = @json(session('auto_generated_recovery_codes'));
    
    // ページ読み込み時にモーダルを自動表示
    document.addEventListener('DOMContentLoaded', function() {
        openModal('autoGeneratedRecoveryCodesModal');
    });
    
    // 回復コードをフォーマット（5桁ごとにハイフン）
    function formatRecoveryCode(code) {
        return code.match(/.{1,5}/g).join('-');
    }
    
    // 回復コードをダウンロード
    function downloadAutoGeneratedRecoveryCodes() {
        const text = autoGeneratedCodes.map(code => formatRecoveryCode(code)).join('\n');
        const blob = new Blob([text], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'recovery-codes-' + new Date().toISOString().split('T')[0] + '.txt';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }
    
    // 回復コードをコピー
    function copyAutoGeneratedRecoveryCodes() {
        const text = autoGeneratedCodes.map(code => formatRecoveryCode(code)).join('\n');
        const copyBtn = event.currentTarget;
        const originalHTML = copyBtn.innerHTML;
        
        navigator.clipboard.writeText(text).then(() => {
            // コピー成功：チェックアイコンを表示
            copyBtn.innerHTML = '<i class="fas fa-check mr-2"></i>{{ __("common.copied") }}';
            copyBtn.classList.remove('bg-gray-600', 'hover:bg-gray-700');
            copyBtn.classList.add('bg-green-600', 'hover:bg-green-700');
            
            // 2秒後に元に戻す
            setTimeout(() => {
                copyBtn.innerHTML = originalHTML;
                copyBtn.classList.remove('bg-green-600', 'hover:bg-green-700');
                copyBtn.classList.add('bg-gray-600', 'hover:bg-gray-700');
            }, 2000);
        }).catch(err => {
            console.error('Copy error:', err);
            alert('{{ __("common.copy_failed") }}');
        });
    }
    
    // 回復コード保管確認チェックボックスの状態を監視
    function checkAutoGeneratedRecoveryCodesSaved() {
        const checkbox = document.getElementById('autoGeneratedRecoveryCodesSavedCheckbox');
        const closeBtn = document.getElementById('autoGeneratedRecoveryCodesCloseBtn');
        
        if (checkbox && closeBtn) {
            closeBtn.disabled = !checkbox.checked;
            
            if (checkbox.checked) {
                closeBtn.classList.remove('opacity-50', 'cursor-not-allowed');
            } else {
                closeBtn.classList.add('opacity-50', 'cursor-not-allowed');
            }
        }
    }
</script>
@endpush
@endif
