{{--
This file is part of Dixlase.

Copyright (C) 2025 exc-D inc.
https://exc-d.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
--}}

{{-- パーシャル用変数のデフォルト値設定 --}}
@php
    $modalId = $modalId ?? 'recoveryCodesModal';
    $title = $title ?? null;
    $codes = $codes ?? [];
    $isAutoGenerated = $isAutoGenerated ?? false;
    $autoOpen = $autoOpen ?? false;
    $isDynamic = $isDynamic ?? false; // JavaScriptで動的に表示する場合
    $error = $error ?? null; // エラーメッセージ（エラー表示モード）
    $clearSessionRoute = $clearSessionRoute ?? null; // セッションクリア用ルート（自動生成時のみ）
    $nextModal = $nextModal ?? null; // 次に開くモーダルのID
@endphp

<x-ui-modal :id="$modalId" :title="$error ? __('common.error') : ($title ?? __('two_fa.recovery_codes.title'))" :icon_type="$error ? 'danger' : 'warning'" :dismissible="false">
    <div class="space-y-4" x-data="recoveryCodesModal(@js($modalId), @js($codes), @js($autoOpen), @js($clearSessionRoute), @js($nextModal))">
        @if($error)
            {{-- エラー表示モード --}}
            <div class="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4">
                <p class="text-sm text-red-800 dark:text-red-200">
                    <i class="fas fa-exclamation-circle mr-2"></i>
                    {{ $error }}
                </p>
            </div>
        @else
            {{-- 回復コード表示モード --}}
            @if($isAutoGenerated)
            <div class="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
                <p class="text-sm text-blue-800 dark:text-blue-200">
                    <i class="fas fa-info-circle mr-2"></i>
                    {{ __('two_fa.recovery_codes.auto_generated_message') }}
                </p>
            </div>
            @endif
            
            <div class="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
                <p class="text-sm text-yellow-800 dark:text-yellow-200">
                    <i class="fas fa-exclamation-triangle mr-2"></i>
                    {!! __('two_fa.recovery_codes.warning') !!}
                </p>
            </div>
            
            <div class="bg-gray-50 dark:bg-gray-800 rounded-lg p-4">
                <div id="{{ $modalId }}-codes-list" class="space-y-2 font-mono text-sm">
                    @if(!$isDynamic)
                        @foreach($codes as $code)
                            <div class="p-2 bg-white dark:bg-gray-700 rounded border border-gray-200 dark:border-gray-600 text-center">
                                {{ implode('-', str_split($code, 5)) }}
                            </div>
                        @endforeach
                    @else
                        <template x-for="code in formattedCodes" :key="code">
                            <div class="p-2 bg-white dark:bg-gray-700 rounded border border-gray-200 dark:border-gray-600 text-center" x-text="code"></div>
                        </template>
                    @endif
                </div>
            </div>
            
            <div class="flex gap-2">
                <button 
                    type="button"
                    @click="downloadCodes()"
                    class="flex-1 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                    <i class="fas fa-download mr-2"></i>{{ __('common.download') }}
                </button>
                <button 
                    type="button"
                    id="{{ $modalId }}-copy-btn"
                    x-ref="copyBtn"
                    @click="copyCodes()"
                    class="flex-1 px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500">
                    <i class="fas fa-copy mr-2"></i>{{ __('common.copy') }}
                </button>
            </div>
            
            <!-- 保管確認チェックボックス -->
            <div class="mt-4 p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg">
                <label class="flex items-start cursor-pointer">
                    <input 
                        type="checkbox" 
                        id="{{ $modalId }}-saved-checkbox"
                        x-model="isSaved"
                        class="mt-1 h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded">
                    <span class="ml-3 text-sm text-red-800 dark:text-red-200 font-semibold">
                        <i class="fas fa-exclamation-circle mr-1"></i>
                        {{ __('two_fa.recovery_codes.confirm_saved') }}
                    </span>
                </label>
            </div>
        @endif
        
        <!-- フッターボタン -->
        <div class="mt-6 flex justify-center border-t border-gray-200 dark:border-gray-700 pt-4">
            <button 
                type="button"
                id="{{ $modalId }}-close-btn"
                @click="handleClose()"
                @if(!$error) :disabled="!canClose" @endif
                class="px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500"
                :class="{ 'opacity-50 cursor-not-allowed': @if(!$error) !canClose @else false @endif }">
                {{ __('common.close') }}
            </button>
        </div>
    </div>
    
    {{-- カスタムフッター（何も表示しない） --}}
    <x-slot name="footer">
        {{-- デフォルトボタンを非表示にするため、空のdivを配置 --}}
        <div style="display: none;"></div>
    </x-slot>
</x-ui-modal>
