{{--
This file is part of Dixlase.

Copyright (C) 2025 exc-D inc.
https://exc-d.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
--}}

@extends('layouts.admin')

@section('content')

    @if(!$isMailServerTested)
        <div class="mb-6 p-4 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded">
            <p class="text-sm text-yellow-800 dark:text-yellow-200">
                <i class="fas fa-exclamation-triangle mr-2"></i>
                {{ __('admin/profile.two_factor_requires_mail_server') }}
            </p>
        </div>
    @else
        <!-- 2FA管理セクション -->
        <div x-data="{
            twoFaMode: '{{ (string) ($twoFaMode?->value ?? 0) }}',
            passkeyEnabled: {{ $currentPasskeyEnabled ? 'true' : 'false' }},
            get isTwoFaDisabled() {
                return this.twoFaMode === '0';
            },
            get isPasskeyDisabled() {
                return this.twoFaMode === '0' || !this.passkeyEnabled;
            }
        }">
            <div :class="{ 'opacity-50 pointer-events-none': isPasskeyDisabled }">
                <x-two-fa.management
                    :twoFaPasskeyEnabled="$twoFaPasskeyEnabled"
                    :twoFaPasskeyDevices="$twoFaPasskeyDevices"
                    :twoFaHasRecoveryCodes="$twoFaHasRecoveryCodes"
                    :twoFaRecoveryCodesCount="$twoFaRecoveryCodesCount"
                    :twoFaTrustedDevices="collect()"
                    :twoFaShowTrustedDevices="false"
                    :routes="[
                        'passkey_register_options' => route('admin.profile.passkey.register-options'),
                        'passkey_register' => route('admin.profile.passkey.register'),
                        'passkey_delete' => route('admin.profile.passkey.revoke', ':id'),
                        'passkey_delete_all' => route('admin.profile.passkey.revoke-all'),
                        'recovery_codes_generate' => route('admin.profile.recovery-codes.generate'),
                    ]"
                    :csrfToken="csrf_token()"
                />
            </div>
        </div>

        {{-- セッションベースのモーダル --}}
        @if(session('auto_generated_recovery_codes'))
            @include('two-fa.partials.recovery-codes-modal', [
                'modalId' => 'profileAutoGeneratedRecoveryCodesModal',
                'title' => __('two_fa.recovery_codes.auto_generated_title'),
                'codes' => session('auto_generated_recovery_codes'),
                'isAutoGenerated' => true,
                'autoOpen' => true
            ])
        @endif

        @if(session('recovery_code_error'))
            @include('two-fa.partials.recovery-codes-modal', [
                'modalId' => 'recoveryCodeErrorModal',
                'error' => session('recovery_code_error'),
                'autoOpen' => true
            ])
        @endif
    @endif

@endsection
