{{--
This file is part of Dixlase.

Copyright (C) 2026 exc-D inc.
https://exc-d.com

Dixlase is dual-licensed. You may use this file under either:

  (a) the GNU Affero General Public License version 3 or later, as
      published by the Free Software Foundation, together with the
      Dixlase Plugin and Theme Exception (see
      LICENSE-EXCEPTIONS for full exception terms); or

  (b) a commercial license agreement obtained from exc-D inc.
      (see LICENSE.commercial, or contact office@exc-d.com).

Unless you have entered into a commercial license agreement, this
file is governed by the AGPL terms below.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
--}}

@extends('layouts.admin')

@section('content')

    <!-- 2FA管理セクション -->
    <div x-data="{
        twoFaMode: '{{ (string) ($twoFaMode?->value ?? 0) }}',
        passkeyEnabled: {{ $currentPasskeyEnabled ? 'true' : 'false' }},
        isTwoFaActuallyDisabled: {{ $isTwoFaActuallyDisabled ? 'true' : 'false' }},
        get isTwoFaDisabled() {
            return this.isTwoFaActuallyDisabled;
        },
        get isPasskeyDisabled() {
            return this.isTwoFaActuallyDisabled || !this.passkeyEnabled;
        }
    }">
        <div class="mb-8">
            
            @if(!$isMailServerTested)
                <x-ui-message
                    type="warning"
                    :message="__('admin/profile/common.two_factor_requires_mail_server')"
                />
            @endif

            {{-- 二段階認証が無効な場合の説明 --}}
            <div x-show="isTwoFaDisabled" class="mb-6">
                <x-ui-message 
                    type="warning" 
                    :message="__('admin/profile/common.two_fa_disabled_notice')"
                />
            </div>

            {{-- Passkeyが無効な場合の説明 --}}
            <div x-show="!isTwoFaDisabled && !passkeyEnabled" class="mb-6">
                <x-ui-message 
                    type="warning" 
                    :message="__('admin/profile/common.passkey_disabled_notice')"
                />
            </div>

            {{-- 二段階認証管理コンポーネント --}}
            <div :class="{ 'opacity-50 pointer-events-none': {{ !$isMailServerTested ? 'true' : 'false' }} }">
                <x-two-fa.management
                :twoFaPasskeyEnabled="$twoFaPasskeyEnabled"
                :twoFaPasskeyDevices="$twoFaPasskeyDevices"
                :twoFaPasskeyMaxDevices="$twoFaPasskeyMaxDevices"
                :twoFaPasskeyCurrentCount="$twoFaPasskeyCurrentCount"
                :canRegisterMorePasskeys="$canRegisterMorePasskeys"
                :twoFaHasRecoveryCodes="$twoFaHasRecoveryCodes"
                :twoFaRecoveryCodesCount="$twoFaRecoveryCodesCount"
                :twoFaTrustedDevices="collect()"
                :twoFaShowTrustedDevices="false"
                :twoFaDisabled="$isTwoFaActuallyDisabled"
                :passkeyDisabled="$isTwoFaActuallyDisabled || !$currentPasskeyEnabled"
                :routes="[
                    'passkey_register_options' => route('admin.profile.passkey.register-options'),
                    'passkey_register' => route('admin.profile.passkey.register'),
                    'passkey_delete' => route('admin.profile.passkey.revoke', ':id'),
                    'passkey_delete_all' => route('admin.profile.passkey.revoke-all'),
                    'recovery_codes_generate' => route('admin.profile.recovery-codes.generate'),
                ]"
                :csrfToken="csrf_token()"
            />
            </div>
        </div>
    </div>

    {{-- セッションベースのモーダル --}}
        @if(session('auto_generated_recovery_codes'))
            @include('two-fa.partials.recovery-codes-modal', [
                'modalId' => 'profileAutoGeneratedRecoveryCodesModal',
                'title' => __('two-fa/recovery-code.auto_generated_title'),
                'codes' => session('auto_generated_recovery_codes'),
                'isAutoGenerated' => true,
                'autoOpen' => true
            ])
        @endif

    @if(session('recovery_code_error'))
        @include('two-fa.partials.recovery-codes-modal', [
            'modalId' => 'recoveryCodeErrorModal',
            'error' => session('recovery_code_error'),
            'autoOpen' => true
        ])
    @endif

@endsection
