{{--
This file is part of Dixlase.

Copyright (C) 2026 exc-D inc. and Dixlase contributors
https://exc-d.com

Dixlase is dual-licensed. You may use this file under either:

  (a) the GNU Affero General Public License version 3 or later, as
      published by the Free Software Foundation, together with the
      Dixlase Plugin and Theme Exception (see
      LICENSE-EXCEPTIONS for full exception terms); or

  (b) a commercial license agreement obtained from exc-D inc.
      (see LICENSE-COMMERCIAL, or contact info@dixlase.org).

Unless you have entered into a commercial license agreement, this
file is governed by the AGPL terms below.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
--}}

@extends('layouts.admin')

@section('content')

    <form method="POST" action="{{ route('admin.profile.two-fa.update') }}" id="profile-two-fa-form">
        @csrf

        <div x-data="twoFaProfileSettings(@js(old('two_fa_mode', (string) ($twoFaMode?->value ?? 0))))" id="two-fa-settings-wrapper">
            {{-- Passkey unregistered warning is omitted as it is handled by the passkey registration promotion modal on the dashboard --}}

            <section class="transition-colors-unified">
                <h2>{{ __('admin/profile/two-fa.two_fa_settings') }}</h2>
                
                @if(!$isMailServerTested)
                    <x-ui-message
                        type="warning"
                        :message="__('admin/profile/common.two_factor_requires_mail_server')"
                    />
                @endif

                {{-- 1. Two-factor authentication mode --}}
                <div :class="{ 'opacity-50 pointer-events-none': {{ !$isMailServerTested ? 'true' : 'false' }} }">
                    <x-two-fa.mode-selector
                        name="two_fa_mode"
                        :value="old('two_fa_mode', (string) ($twoFaMode?->value ?? 0))"
                        :globalSetting="$twoFaForceMode"
                        :excludeUseProfileSetting="true"
                        :columns="3"
                        :isProfile="true"
                        :isTwoFaEditable="$isTwoFaEditable"
                        xModel="twoFaMode"
                    />
                </div>
            </section>
        </div>

    </form>

    {{-- Session-based modal --}}
    @if(session('auto_generated_recovery_codes'))
        @include('two-fa.partials.recovery-codes-modal', [
            'modalId' => 'profileAutoGeneratedRecoveryCodesModal',
            'title' => __('two-fa/recovery-code.auto_generated_title'),
            'codes' => session('auto_generated_recovery_codes'),
            'isAutoGenerated' => true,
            'autoOpen' => true,
            'nextModal' => session('prompt_passkey_registration') ? 'passkeyPromptModal' : null
        ])
    @endif

    @if(session('recovery_code_error'))
        @include('two-fa.partials.recovery-codes-modal', [
            'modalId' => 'recoveryCodeErrorModal',
            'error' => session('recovery_code_error'),
            'autoOpen' => true
        ])
    @endif
    
    {{-- Passkey registration promotion modal --}}
    @if(session('prompt_passkey_registration'))
        @include('two-fa.partials.passkey-prompt-modal', [
            'modalId' => 'passkeyPromptModal',
            'hasRecoveryModal' => session('auto_generated_recovery_codes') ? true : false
        ])
    @endif

@endsection

@section('save')
    @if($isMailServerTested)
        <x-admin.save-button
            id_confirmation="confirmProfileTwoFactorModal"
            :label="__('common.update')"
            :title="__('admin/profile/common.confirm_title')"
            :message="__('admin/profile/common.confirm_message')"
            :confirm_label="__('common.update')"
            :cancel_label="__('common.cancel')"
            form="profile-two-fa-form"
        />
    @endif
@endsection
