<?php

/**
 * This file is part of Dixlase.
 *
 * Copyright (C) 2026 exc-D inc.
 * https://exc-d.com
 *
 * Dixlase is dual-licensed. You may use this file under either:
 *
 *   (a) the GNU Affero General Public License version 3 or later, as
 *       published by the Free Software Foundation, together with the
 *       Dixlase Plugin and Theme Exception (see
 *       LICENSE-EXCEPTIONS for full exception terms); or
 *
 *   (b) a commercial license agreement obtained from exc-D inc.
 *       (see LICENSE.commercial, or contact info@dixlase.org).
 *
 * Unless you have entered into a commercial license agreement, this
 * file is governed by the AGPL terms below.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

use Illuminate\Support\Facades\DB;

if (! function_exists('is_vite_dev_server')) {
    /**
     * Determine if Vite dev server is enabled
     * Returns true if in local environment and hot file exists
     */
    function is_vite_dev_server(): bool
    {
        return file_exists(public_path('hot'));
    }
}

if (! function_exists('get_csp_nonce_attr')) {
    /**
     * Get CSP nonce attribute
     */
    function get_csp_nonce_attr(): string
    {
        return function_exists('csp_nonce_attr') ? ' '.csp_nonce_attr() : '';
    }
}

if (! function_exists('render_vite_assets')) {
    /**
     * Generate asset tags for Vite dev server
     *
     * @param  array  $files  Array of file paths to load with Vite
     * @param  bool  $addXCloak  Whether to add x-cloak styles
     * @param  bool  $addFoucPrevention  Whether to add FOUC prevention styles
     */
    function render_vite_assets(array $files, bool $addXCloak = true, bool $addFoucPrevention = false): string
    {
        $output = '';

        if (! empty($files)) {
            // Get CSP nonce first (returns same value as it's a singleton)
            $nonce = function_exists('csp_nonce') ? csp_nonce() : null;

            // Render Vite directive (supports multiple entry points with array syntax)
            $viteOutput = \Illuminate\Support\Facades\Blade::render(
                '@vite(['.implode(', ', array_map(fn ($file) => "'{$file}'", $files)).'])'
            );

            // Replace nonce in script tags generated by Vite
            if ($nonce) {
                // Remove existing nonce attribute then add new nonce
                $viteOutput = preg_replace(
                    '/<script\s+nonce="[^"]*"\s*/i',
                    '<script ',
                    $viteOutput
                );
                // Add custom nonce
                $viteOutput = preg_replace(
                    '/<script\s+(type="module"\s+)?src=/i',
                    '<script nonce="'.$nonce.'" $1src=',
                    $viteOutput
                );
            }

            $output .= $viteOutput;
        }

        if ($addXCloak) {
            $output .= '<style>[x-cloak]{display:none!important;}</style>';
        }

        if ($addFoucPrevention) {
            $output .= '<style>body{opacity:0;visibility:hidden;}</style>';
            $nonceAttr = get_csp_nonce_attr();
            $output .= <<<HTML
<script{$nonceAttr}>
    window.addEventListener('load', () => {
        document.body.style.visibility = 'visible';
        document.body.style.opacity = '1';
    });
</script>
HTML;
        }

        return $output;
    }
}

if (! function_exists('render_css_link')) {
    /**
     * Generate CSS link tag
     *
     * @param  string  $href  CSS file URL
     */
    function render_css_link(string $href): string
    {
        return '<link rel="stylesheet" href="'.$href.'">';
    }
}

if (! function_exists('render_js_script')) {
    /**
     * Generate JS script tag (with CSP nonce support)
     *
     * @param  string  $src  JS file URL
     */
    function render_js_script(string $src): string
    {
        $nonce = get_csp_nonce_attr();

        return '<script type="module" src="'.$src.'"'.$nonce.'></script>';
    }
}

if (! function_exists('render_x_cloak_style')) {
    /**
     * Generate style tag for x-cloak (with CSP nonce support)
     */
    function render_x_cloak_style(): string
    {
        $nonce = get_csp_nonce_attr();

        return '<style'.$nonce.'>[x-cloak]{display:none!important;}</style>';
    }
}

if (! function_exists('get_active_theme_directory')) {
    /**
     * Get active theme directory name
     */
    function get_active_theme_directory(): string
    {
        static $themeDirectory = null;

        if ($themeDirectory === null) {
            try {
                $themeSetting = DB::table('theme_settings')
                    ->where('key', 'enabled_theme_id')
                    ->first();

                if ($themeSetting && $themeSetting->value) {
                    $activeTheme = \App\Models\Theme::find((int) $themeSetting->value);
                    $themeDirectory = $activeTheme ? $activeTheme->directory : 'DixlaseOnePage';
                } else {
                    $themeDirectory = 'DixlaseOnePage';
                }
            } catch (\Exception $e) {
                $themeDirectory = 'DixlaseOnePage';
            }
        }

        return $themeDirectory;
    }
}

if (! function_exists('load_assets_from_manifest')) {
    /**
     * Load assets from manifest.json
     *
     * @param  string  $manifestPath  Manifest file path
     * @param  string  $assetBasePath  Base path for assets
     * @param  array  $files  Array of files to load
     * @param  string  $sourceBasePath  Base path for source files (for manifest keys)
     * @param  array  $alternativeKeys  Alternative manifest key pattern
     */
    function load_assets_from_manifest(
        string $manifestPath,
        string $assetBasePath,
        array $files,
        string $sourceBasePath = '',
        array $alternativeKeys = []
    ): string {
        $output = '';

        if (! file_exists($manifestPath) || empty($files)) {
            return $output;
        }

        $manifest = json_decode(file_get_contents($manifestPath), true);
        if (empty($manifest)) {
            return $output;
        }

        foreach ($files as $file) {
            $manifestKey = $sourceBasePath ? "{$sourceBasePath}/{$file}" : $file;
            $keysToTry = [$manifestKey, ...$alternativeKeys, $file];

            // Manifest keys for plugin/theme may be relative paths from resources/src/
            if ($sourceBasePath && preg_match('#(?:plugins|themes)/[^/]+/(resources/src.*)$#', $sourceBasePath, $m)) {
                $keysToTry[] = "{$m[1]}/{$file}";
            }

            foreach ($keysToTry as $key) {
                if (isset($manifest[$key])) {
                    $entry = $manifest[$key];

                    // CSS files (when the entry itself is CSS)
                    if (isset($entry['file']) && str_ends_with($entry['file'], '.css')) {
                        $output .= render_css_link(asset($assetBasePath.$entry['file']));
                    }

                    // CSS files (CSS associated with JS entry)
                    if (isset($entry['css'])) {
                        foreach ($entry['css'] as $css) {
                            $output .= render_css_link(asset($assetBasePath.$css));
                        }
                    }

                    // JS files
                    if (isset($entry['file']) && str_ends_with($entry['file'], '.js')) {
                        $output .= render_js_script(asset($assetBasePath.$entry['file']));
                    }

                    // Fonts and other assets
                    if (isset($entry['assets'])) {
                        foreach ($entry['assets'] as $assetFile) {
                            $ext = pathinfo($assetFile, PATHINFO_EXTENSION);
                            if (in_array($ext, ['woff', 'woff2', 'ttf', 'otf', 'eot'])) {
                                $output .= '<link rel="preload" as="font" href="'.asset($assetBasePath.$assetFile).'" type="font/'.$ext.'" crossorigin="anonymous">';
                            }
                        }
                    }

                    break;
                }
            }
        }

        return $output;
    }
}

if (! function_exists('load_static_assets')) {
    /**
     * Load static asset files directly (for fallback)
     *
     * @param  string  $assetBasePath  Base path for assets
     * @param  array  $files  Array of files to load
     */
    function load_static_assets(string $assetBasePath, array $files): string
    {
        $output = '';

        foreach ($files as $file) {
            $filePath = public_path("{$assetBasePath}/{$file}");
            if (file_exists($filePath)) {
                $ext = pathinfo($file, PATHINFO_EXTENSION);
                if ($ext === 'css') {
                    $output .= render_css_link(asset($assetBasePath.'/'.$file));
                } elseif ($ext === 'js') {
                    $output .= render_js_script(asset($assetBasePath.'/'.$file));
                }
            }
        }

        return $output;
    }
}

if (! function_exists('load_assets')) {
    /**
     * Function to dynamically load assets (for admin panel)
     *
     * @param  string  $type  Asset type ('common', 'admin', 'theme', 'plugin')
     * @param  string|null  $name  Directory name for theme or plugin (null for common, admin)
     * @param  array  $files  List of JS or CSS files to load
     */
    function load_assets(string $type, ?string $name, array $files): string
    {
        $output = '';
        $basePath = match ($type) {
            'common' => 'resources/src/common',
            'admin' => 'resources/src/admin',
            'theme' => "themes/{$name}/resources/src",
            'plugin' => "plugins/{$name}/resources/src",
            default => throw new InvalidArgumentException("Invalid type: {$type}"),
        };

        if (is_vite_dev_server()) {
            $viteFiles = array_map(fn ($file) => "{$basePath}/{$file}", $files);
            $output .= render_vite_assets($viteFiles, true, true);
        } else {
            $manifestPath = match ($type) {
                'common', 'admin' => public_path('assets/build/manifest.json'),
                'theme' => public_path("assets/themes/{$name}/manifest.json"),
                'plugin' => public_path("assets/plugins/{$name}/manifest.json"),
            };

            $assetBasePath = match ($type) {
                'common', 'admin' => 'assets/build/',
                'theme' => "assets/themes/{$name}/",
                'plugin' => "assets/plugins/{$name}/",
            };

            $output .= load_assets_from_manifest($manifestPath, $assetBasePath, $files, $basePath);

            // Fallback to static assets if manifest does not exist
            if ($output === '' && ! file_exists($manifestPath)) {
                $output .= load_static_assets(rtrim($assetBasePath, '/'), $files);
            }
        }

        return $output;
    }
}

if (! function_exists('get_plugin_declared_assets')) {
    /**
     * Get declared asset information from plugin's plugin.json
     *
     * @return array{common: string[], admin: string[], front: string[]}|false|null
     *                                                                              Array if asset declaration exists, false if no assets, null if undeclared
     */
    function get_plugin_declared_assets(string $pluginDirectory): array|false|null
    {
        static $cache = [];

        if (array_key_exists($pluginDirectory, $cache)) {
            return $cache[$pluginDirectory];
        }

        $pluginJsonPath = base_path("plugins/{$pluginDirectory}/plugin.json");
        if (! file_exists($pluginJsonPath)) {
            $cache[$pluginDirectory] = null;

            return null;
        }

        $data = json_decode(file_get_contents($pluginJsonPath), true);
        if (json_last_error() !== JSON_ERROR_NONE) {
            $cache[$pluginDirectory] = null;

            return null;
        }

        $assets = $data['declares']['assets'] ?? null;

        // No assets if assets === false
        if ($assets === false) {
            $cache[$pluginDirectory] = false;

            return false;
        }

        // Return as-is if assets is an array
        if (is_array($assets)) {
            $cache[$pluginDirectory] = $assets;

            return $assets;
        }

        // Undeclared
        $cache[$pluginDirectory] = null;

        return null;
    }
}

if (! function_exists('get_theme_declared_assets')) {
    /**
     * Get asset information declared in the theme's theme.json
     *
     * @return array{common: string[], admin: string[], front: string[]}|false|null
     *                                                                              Array if asset declaration exists, false if no assets, null if undeclared
     */
    function get_theme_declared_assets(string $themeDirectory): array|false|null
    {
        static $cache = [];

        if (array_key_exists($themeDirectory, $cache)) {
            return $cache[$themeDirectory];
        }

        $themeJsonPath = base_path("themes/{$themeDirectory}/theme.json");
        if (! file_exists($themeJsonPath)) {
            $cache[$themeDirectory] = null;

            return null;
        }

        $data = json_decode(file_get_contents($themeJsonPath), true);
        if (json_last_error() !== JSON_ERROR_NONE) {
            $cache[$themeDirectory] = null;

            return null;
        }

        $assets = $data['assets'] ?? null;

        if ($assets === false) {
            $cache[$themeDirectory] = false;

            return false;
        }

        if (is_array($assets)) {
            $cache[$themeDirectory] = $assets;

            return $assets;
        }

        $cache[$themeDirectory] = null;

        return null;
    }
}

if (! function_exists('load_active_assets')) {
    /**
     * For admin panel: Load assets of active theme and plugins
     * Skip plugin assets when plugin safe mode is enabled
     */
    function load_active_assets(): string
    {
        $output = '';

        // Load plugin and theme assets first
        // (to execute Alpine.data() registration before Alpine.start() in common)

        // Skip plugin assets in plugin safe mode
        if (! session('safe_mode_plugins')) {
            // Load assets of enabled plugins
            try {
                $activePlugins = DB::table('plugins')->whereNotNull('enabled_at')->get();
                foreach ($activePlugins as $plugin) {
                    $declaredAssets = get_plugin_declared_assets($plugin->directory);

                    // Skip if assets === false or undeclared
                    if ($declaredAssets === false || $declaredAssets === null) {
                        continue;
                    }

                    $commonAssets = $declaredAssets['common'] ?? [];
                    $adminAssets = $declaredAssets['admin'] ?? [];
                    $allAssets = array_merge($commonAssets, $adminAssets);

                    if (! empty($allAssets)) {
                        $output .= load_assets('plugin', $plugin->directory, $allAssets);
                    }
                }
            } catch (\Exception $e) {
                // Skip if plugin table does not exist
            }
        }

        // Load assets of active theme
        $themeDirectory = get_active_theme_directory();
        $themeDeclaredAssets = get_theme_declared_assets($themeDirectory);

        if (is_array($themeDeclaredAssets)) {
            $themeCommonAssets = $themeDeclaredAssets['common'] ?? [];
            $themeAdminAssets = $themeDeclaredAssets['admin'] ?? [];
            $allThemeAssets = array_merge($themeCommonAssets, $themeAdminAssets);

            if (! empty($allThemeAssets)) {
                $output .= load_assets('theme', $themeDirectory, $allThemeAssets);
            }
        }

        // Load Tailwind CSS first (Preflight + utility base)
        $output .= load_assets('common', null, ['css/tailwind.css']);

        // Load admin panel assets (load first to execute Alpine.data() registration before Alpine.start())
        $output .= load_assets('admin', null, ['js/app.js', 'scss/style.scss']);

        // Load common assets (Alpine.start() is executed here)
        $output .= load_assets('common', null, ['js/app.js', 'scss/style.scss']);

        return $output;
    }
}

if (! function_exists('load_theme_assets')) {
    /**
     * For theme: Load theme assets
     *
     * @param  array  $files  Array of files to load (e.g. ['css/style.css', 'js/app.js'])
     * @param  string|null  $themeDirectory  Theme directory name (active theme if null)
     */
    function load_theme_assets(array $files, ?string $themeDirectory = null): string
    {
        $output = '';
        $themeDirectory = $themeDirectory ?? get_active_theme_directory();

        if (is_vite_dev_server()) {
            $viteFiles = array_map(
                fn ($file) => "themes/{$themeDirectory}/resources/src/front/{$file}",
                $files
            );
            $output .= render_vite_assets($viteFiles, false, false);
        } else {
            $themeAssetPath = "assets/themes/{$themeDirectory}";
            $manifestPath = public_path("{$themeAssetPath}/manifest.json");

            if (file_exists($manifestPath)) {
                $alternativeKeys = array_map(
                    fn ($file) => "themes/{$themeDirectory}/resources/src/front/{$file}",
                    $files
                );
                $output .= load_assets_from_manifest(
                    $manifestPath,
                    $themeAssetPath.'/',
                    $files,
                    'resources/src/front',
                    $alternativeKeys
                );
            } else {
                // Load files directly if manifest does not exist
                $output .= load_static_assets($themeAssetPath, $files);
            }
        }

        return $output;
    }
}

if (! function_exists('load_plugin_assets')) {
    /**
     * For plugin: Load plugin assets
     *
     * @param  string  $pluginDirectory  Plugin directory name
     * @param  array  $files  Array of files to load
     */
    function load_plugin_assets(string $pluginDirectory, array $files): string
    {
        $output = '';

        if (is_vite_dev_server()) {
            $viteFiles = array_map(
                fn ($file) => "plugins/{$pluginDirectory}/resources/src/{$file}",
                $files
            );
            $output .= render_vite_assets($viteFiles, false, false);
        } else {
            $pluginAssetPath = "assets/plugins/{$pluginDirectory}";
            $manifestPath = public_path("{$pluginAssetPath}/manifest.json");

            if (file_exists($manifestPath)) {
                $output .= load_assets_from_manifest(
                    $manifestPath,
                    $pluginAssetPath.'/',
                    $files,
                    "plugins/{$pluginDirectory}/resources/src"
                );
            } else {
                $output .= load_static_assets($pluginAssetPath, $files);
            }
        }

        return $output;
    }
}

if (! function_exists('load_core_assets')) {
    /**
     * For Core: Load Core assets (Tailwind, etc.)
     *
     * @param  array  $files  Array of files to load
     * @param  string  $type  Asset type ('common', 'admin', 'front')
     */
    function load_core_assets(array $files, string $type = 'common'): string
    {
        $output = '';
        $basePath = "resources/src/{$type}";

        if (is_vite_dev_server()) {
            $viteFiles = array_map(fn ($file) => "{$basePath}/{$file}", $files);
            $output .= render_vite_assets($viteFiles, false, false);
        } else {
            // Load built Core CSS
            $coreCssFiles = [
                'assets/build/css/common.css',
            ];
            foreach ($coreCssFiles as $cssFile) {
                if (file_exists(public_path($cssFile))) {
                    $output .= render_css_link(asset($cssFile));
                }
            }

            // Load assets from manifest.json
            $output .= load_assets_from_manifest(
                public_path('assets/build/manifest.json'),
                'assets/build/',
                $files,
                $basePath
            );
        }

        return $output;
    }
}

if (! function_exists('load_front_assets')) {
    /**
     * For front pages: load Core and theme assets
     * Skip theme assets when theme safe mode is enabled
     *
     * @param  array  $coreFiles  Core front-end asset files
     * @param  array  $themeFiles  Theme-specific asset files
     */
    function load_front_assets(array $coreFiles = [], array $themeFiles = []): string
    {
        $output = '';

        // Load Core assets
        if (! empty($coreFiles)) {
            $output .= load_core_assets($coreFiles, 'front');
        } else {
            // Load Tailwind even if coreFiles is empty
            if (! is_vite_dev_server()) {
                $coreCssFile = 'assets/build/css/common.css';
                if (file_exists(public_path($coreCssFile))) {
                    $output .= render_css_link(asset($coreCssFile));
                }
            }
        }

        // Skip theme assets in theme safe mode
        if (! session('safe_mode_theme') && ! empty($themeFiles)) {
            $output .= load_theme_assets($themeFiles);
        }

        // Add styles for x-cloak
        $output .= render_x_cloak_style();

        return $output;
    }
}

if (! function_exists('load_auth_assets')) {
    /**
     * For auth pages: load only common assets (excludes admin panel, theme, and plugin assets)
     */
    function load_auth_assets(): string
    {
        $output = '';

        // Load Tailwind CSS first (Preflight + utility base)
        $output .= load_assets('common', null, ['css/tailwind.css']);

        // Load admin panel assets (login form styles, etc.)
        $output .= load_assets('admin', null, ['js/app.js', 'scss/style.scss']);

        // Load common assets (Alpine.js, etc.)
        $output .= load_assets('common', null, ['js/app.js', 'scss/style.scss']);

        // Load dark mode script (CSP compatible)
        if (is_vite_dev_server()) {
            $output .= render_vite_assets(['resources/src/auth/js/dark-mode.js'], false, false);
        } else {
            $manifestPath = public_path('assets/build/manifest.json');
            $assetBasePath = 'assets/build/';
            $output .= load_assets_from_manifest(
                $manifestPath,
                $assetBasePath,
                ['js/dark-mode.js'],
                'resources/src/auth'
            );
        }

        // Add styles for x-cloak
        $output .= render_x_cloak_style();

        return $output;
    }
}

if (! function_exists('load_mail_verification_assets')) {
    /**
     * For email verification page: load Tailwind CSS and dark mode script (strict CSP compatible)
     *
     * @param  string  $scriptType  'success' or 'error'
     */
    function load_mail_verification_assets(string $scriptType = 'success'): string
    {
        $output = '';

        if (is_vite_dev_server()) {
            // Development environment: load via Vite
            // Load tailwind.css (utility classes) + style.scss (component/custom styles)
            // Load together in a single @vite() call (prevents @vite/client duplication)
            $output .= render_vite_assets([
                'resources/src/common/css/tailwind.css',
                'resources/src/common/scss/style.scss',
                'resources/src/components/mail-server/js/dark-mode.js',
                "resources/src/components/mail-server/js/verification-{$scriptType}.js",
            ], false, false);
        } else {
            // Production environment: load built files
            $manifestPath = public_path('assets/build/manifest.json');
            $assetBasePath = 'assets/build/';

            // Tailwind CSS (utility classes)
            $output .= load_assets_from_manifest(
                $manifestPath,
                $assetBasePath,
                ['css/tailwind.css'],
                'resources/src/common'
            );

            // Component/Custom styles
            $output .= load_assets_from_manifest(
                $manifestPath,
                $assetBasePath,
                ['scss/style.scss'],
                'resources/src/common'
            );

            // Dark mode script
            $output .= load_assets_from_manifest(
                $manifestPath,
                $assetBasePath,
                ['js/dark-mode.js'],
                'resources/src/components/mail-server'
            );

            // Authentication page specific script
            $output .= load_assets_from_manifest(
                $manifestPath,
                $assetBasePath,
                ["js/verification-{$scriptType}.js"],
                'resources/src/components/mail-server'
            );
        }

        return $output;
    }
}
